---
title: "EmploiEC: update data"
author: "CPESR"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(dplyr.summarise.inform = FALSE)
knitr::opts_chunk$set(fig.asp = 9/16, fig.retina = 2)

library(tidyverse)
library(ggcpesrthemes)
library(ggrepel)

theme_set(theme_cpesr())
theme_cpesr_setup(authors = "Julien Gossa", source = "https://github.com/cpesr/RFC/")
```

## Chargement des données sources  

### Sections CNU

```{r load.cnu.section, results='asis'}
cnu.sections <- read.csv2("data/cpesr-cnu-sections.csv")

cnu.sections %>% spoiler_table("cnu.section", trim=Inf)
```

```{r load.cnu.perimetre, results='asis'}
cnu.périmètres <- bind_rows(
  cnu.sections %>% transmute(Périmètre = "Section", Périmètre.ID = as.character(SectionCNU.ID), Périmètre.label = SectionCNU),
  cnu.sections %>% transmute(Périmètre = "Groupe", Périmètre.ID = GroupeCNU.ID, Périmètre.label = GroupeCNU) %>% unique(),
  cnu.sections %>% transmute(Périmètre = "Grande discipline", Périmètre.ID = GrandeDisciplineCNU.ID, Périmètre.label = GrandeDisciplineCNU) %>% unique(),
  data.frame("Périmètre" = "Ensemble", Périmètre.ID = "Ensemble", Périmètre.label = "Ensemble")) %>%
  na.omit()

cnu.périmètres %>% spoiler_table("cnu.périmètres", trim=Inf)
```

### Enseignants

```{r load.ens, results='asis'}
ens <- read.csv2("data/fr-esr-enseignants-titulaires-esr-public.csv") %>% 
  filter(Code.categorie.personnels %in% c("MCF","PR")) %>%
  group_by(Rentrée,code_section_cnu,Code.categorie.personnels) %>%
  summarise(effectif = sum(effectif,na.rm = TRUE)) %>%
  pivot_wider(names_from = Code.categorie.personnels, values_from = effectif) %>%
  ungroup() %>%
  transmute(
    Année = Rentrée,
    SectionCNU.ID = code_section_cnu,
    Effectif.MCF = MCF,
    Effectif.PR = PR
    ) %>%
  left_join(cnu.sections)


ens <- bind_rows(
ens %>%
  transmute(
    Périmètre = "Section",
    Périmètre.ID = as.character(SectionCNU.ID),
    Année,
    Effectif.MCF,
    Effectif.PR
  ),
ens %>%
  group_by(
    Périmètre = "Groupe",
    Périmètre.ID = as.character(GroupeCNU.ID),
    Année) %>%
  summarise(
    Effectif.MCF = sum(Effectif.MCF, na.rm = T),
    Effectif.PR = sum(Effectif.PR, na.rm = T)
  ),
ens %>%
  group_by(
    Périmètre = "Grande discipline",
    Périmètre.ID = as.character(GrandeDisciplineCNU.ID),
    Année) %>%
  summarise(
    Effectif.MCF = sum(Effectif.MCF, na.rm = T),
    Effectif.PR = sum(Effectif.PR, na.rm = T)
  ),
ens %>%
  group_by(
    Périmètre = "Ensemble",
    Périmètre.ID = "Ensemble",
    Année) %>%
  summarise(
    Effectif.MCF = sum(Effectif.MCF, na.rm = T),
    Effectif.PR = sum(Effectif.PR, na.rm = T)
  )
)

ens %>% spoiler_table("ens", trim=Inf)
```

### Etudiants

```{r load.etu, results='asis'}
etu <- read.csv2("data/fr-esr-statistiques-sur-les-effectifs-d-etudiants-inscrits-par-etablissement-hcp.csv") %>%
  filter(Attention == "Sans double compte des établissements-composantes pour les EPE") %>%
  #filter(Type.d.établissement == "Université" ) %>%
  transmute(
    Année = rentree,
    Ensemble = replace_na(Nombre.d.étudiants.inscrits..inscriptions.principales..hors.doubles.inscriptions.CPGE,0) - replace_na(Nombre.d.étudiants.préparant.un.diplôme.d.État.d.infirmier.en.IFSI,0),
    DEG=Grande.discipline...Droit..sciences.économiques..AES,
    Sans=Grande.discipline...Interdisciplinaire,
    LLASHS=replace_na(Grande.discipline...Lettres..langues.et.sciences.humaines,0) + replace_na(Grande.discipline...STAPS,0),
    Santé = Grande.discipline...Santé,
    ST = Grande.discipline...Sciences.et.sciences.de.l.ingénieur,
    Pharma = Discipline...Pharmacie      
  ) %>% 
  pivot_longer(-c(Année), names_to = "Périmètre.ID", values_to = "Effectif.ETU") %>%
  group_by(Année, Périmètre.ID) %>%
  summarise(Effectif.ETU = sum(Effectif.ETU, na.rm = TRUE)) %>%
  mutate(
    Périmètre.ID = na_if(Périmètre.ID,"NA"),
    Périmètre=ifelse(Périmètre.ID == "Ensemble", "Ensemble","Grande discipline")) %>%
  filter(Année > 2009) %>%
  filter(Année <= max(ens$Année))

etu %>% spoiler_table("etu", trim=Inf)
```

### Fiches démographiques CNU

```{r load.cnu.fd, results='asis'}
cnu.fd <- read.csv2("data/cpesr-emplois-ec-cnu.csv")

cnu.fd %>% spoiler_table("cnu.fd", trim=Inf)
```

### DGRH

```{r fun.aggreg}
sections_agregations <- function(df) {
  df <- df %>% left_join(cnu.sections) 
    
  bind_rows(
    df %>%
      group_by(Année, Périmètre = "Ensemble", Périmètre.ID = "Ensemble") %>%
      summarise(across(starts_with(c("Concours","Qualifications")),
                         ~ sum(.x,na.rm=FALSE))),
    df %>%
      group_by(Année, Périmètre = "Grande discipline", Périmètre.ID = GrandeDisciplineCNU.ID) %>%
      summarise(across(starts_with(c("Concours","Qualifications")),
                         ~ sum(.x,na.rm=FALSE))),
    df %>%
      group_by(Année, Périmètre = "Groupe", Périmètre.ID = GroupeCNU.ID) %>%
      summarise(across(starts_with(c("Concours","Qualifications")),
                         ~ sum(.x,na.rm=FALSE))),
    df %>%
      group_by(Année, Périmètre = "Section", Périmètre.ID = as.character(SectionCNU.ID)) %>%
      summarise(across(starts_with(c("Concours","Qualifications")),
                         ~ sum(.x,na.rm=FALSE)))
  )
}
```

```{r dgrh, results='asis'}
dgrh.raw <- read.csv2("data/cpesr-emplois-ec-dgrh.csv") 
dgrh <- sections_agregations(dgrh.raw)
dgrh %>% spoiler_table("dgrh", trim = 20)
```

### DPE

```{r dpe, results='asis'}
dpe.raw <- read.csv2("utils/dpe-excavator/cpesr-emplois-ec-dpe.csv") %>%
  select(-SectionCNU, -Concours.TauxCouverture.MCF, -Concours.TauxCouverture.PR) %>%
  mutate(Concours.Postes.PR = ifelse(SectionCNU.ID > 6, Concours.Postes.PR, NA)) %>% # Section à aggrégation
  mutate(SectionCNU.ID = recode(SectionCNU.ID, `39` = 85L, `40` = 86L, `41` = 87L)) # Pharma
dpe <- sections_agregations(dpe.raw)
dpe %>% spoiler_table("dpe", trim = 20)
```



## Données temporaires galaxie

```{r galaxie, results='asis'}
dir <- "utils/galaxie-excavator/"

galaxie <- data.frame() 
for(file in list.files(dir, pattern = "^galaxie......csv$")) {
  an <- str_sub(file,9,12)
  gal <- read.table(paste0(dir,file), header=TRUE, sep=",", quote='"') %>%
    mutate(Année = an) 
  galaxie <- bind_rows(galaxie,gal)
}

galaxie <- galaxie %>% 
  rename(SectionCNU.ID = Section) %>%
  left_join(cnu.sections) %>%
  mutate(Année = as.integer(Année))

galaxie <- bind_rows(
  galaxie %>%
    group_by(Année, Corps, Périmètre = "Ensemble", Périmètre.ID = "Ensemble") %>%
    summarise(Concours.Postes = n()), 
  galaxie %>%
    group_by(Année, Corps, Périmètre = "Grande discipline", Périmètre.ID = GrandeDisciplineCNU.ID) %>%
    summarise(Concours.Postes = n()), 
  galaxie %>%
    group_by(Année, Corps, Périmètre = "Groupe", Périmètre.ID = GroupeCNU.ID) %>%
    summarise(Concours.Postes = n()), 
  galaxie %>%
    group_by(Année, Corps, Périmètre = "Section", Périmètre.ID = as.character(SectionCNU.ID)) %>%
    summarise(Concours.Postes = n())
) %>%
  pivot_wider(names_from = Corps, values_from = Concours.Postes, names_prefix = "Concours.Postes.")

galaxie %>% spoiler_table("galaxie", trim=Inf)
```



## Fusions

```{r emploisEC, results='asis'}

concours <- bind_rows(
  dpe %>% 
    mutate(Source = "DGRH") %>%
    filter(Année < min(cnu.fd$Année)),
  cnu.fd %>%
    mutate(Source = "CNU"),
  galaxie %>%
    mutate(Source = "Galaxie") %>%
    filter(Année > max(cnu.fd$Année))
) %>%
  select(-Source, everything(), Source)

emploisEC <- cnu.périmètres %>%
  right_join(concours) %>%
  left_join(ens) %>%
  left_join(etu) %>%
  mutate(
    Année = as.factor(Année),
    Périmètre = factor(Périmètre, levels=c("Ensemble","Grande discipline","Groupe","Section"))) %>%
  arrange(Périmètre,Périmètre.ID,Année) %>%
  group_by(Périmètre,Périmètre.ID) %>%
  mutate(
    Effectif.EC = Effectif.MCF+Effectif.PR,
    Contexte.TauxEncadrement = Effectif.EC / Effectif.ETU * 100,
    Contexte.EvolRéelle = Effectif.EC - first(Effectif.EC),
    Contexte.EvolNécessaire = (Effectif.ETU / first(Effectif.ETU) - 1) * first(Effectif.EC) 
  ) %>%
  mutate(
    kpi.MCF.TauxTension = Concours.Candidats.MCF / Concours.Postes.MCF,
    kpi.MCF.TauxRéussite = Concours.Recrutés.MCF / Concours.Candidats.MCF,
    kpi.MCF.SansPoste = Concours.Candidats.MCF - Concours.Recrutés.MCF,
    kpi.MCF.TauxSélection = Concours.Recrutés.MCF / Qualification.Candidats.MCF,
    kpi.MCF.TauxSélection.Qualification = Qualification.Qualifiés.MCF / Qualification.Candidats.MCF,
    kpi.MCF.TauxSélection.Concours = Concours.Recrutés.MCF / Qualification.Qualifiés.MCF,
    kpi.MCF.TauxSélection.QualifVsConcours = (Qualification.Qualifiés.MCF - Concours.Recrutés.MCF) / (Qualification.Candidats.MCF-Concours.Recrutés.MCF),
    kpi.PériodeRenouvellement = (Effectif.MCF+Effectif.PR) / Concours.Recrutés.MCF
  ) %>%
  ungroup() %>%
  arrange(Périmètre, Année, Périmètre.ID)

emploisEC %>% spoiler_table("emploisEC", trim = Inf)
```

```{r check}
check_emploisEC <- function() {
  emploisEC %>%
    group_by(Périmètre,Périmètre.ID,Périmètre.label) %>%
    summarise(nb_lignes = n()) %>%
    filter(nb_lignes != 22)
}

check_emploisEC() %>% filter(nb_lignes != 13) %>% kableExtra::kable()
```



## Ecriture des données

```{r write}
write.csv2(emploisEC, "data/cpesr-emplois-ec.csv", row.names = FALSE)
```

## Effacement du cache

```{r clearcache}
unlink("emploiEC/cpesr-emploiEC-rapport_cache/*", recursive = TRUE)
```
