---
title: "CNU Excavator"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(ggcpesrthemes)

as.numeric_cnu <- function(x) {
  if(is.numeric(x)) return(x)
  ifelse(
    str_detect(x,"div"),
    Inf,
    readr::parse_number(x,trim_ws = T, locale = readr::locale(decimal_mark = ",", grouping_mark = " "))
  )
}

clean_perimetre <- function(df,perimetre.nom,perimetre.col,data.col.start,data.col.end) {
  df %>%
  filter(Périmètre == perimetre.nom) %>%
    mutate(Périmètre.ID = as.character(!!as.name(perimetre.col))) %>%
    slice_head(by=c(Année, Périmètre.ID)) %>% 
    select(
      Périmètre,Périmètre.ID,Année,
      !!as.name(data.col.start):!!as.name(data.col.end)
    )
}

cnu.sections <- read.csv2("../../data/cpesr-cnu-sections.csv")
```

## Qualifications 

```{r qualif.funs}
clean_qualif <- function(csvfile) {
  
  qualif <- read.csv(csvfile, header = FALSE) %>%
    transmute(
      SectionCNU.ID = as.numeric(V1),
      Année = as.numeric(V4),
      Qualification.Candidats.PR = as.numeric_cnu(V5),
      Qualification.Candidats.PR.femmes = as.numeric_cnu(V6) /100,
      Qualification.Qualifiés.PR = as.numeric_cnu(V8),
      Qualification.Qualifiés.PR.femmes = as.numeric_cnu(V9) /100,
      #Qualification.Ratio.PR = as.numeric_cnu(V9) /100,
      Qualification.Candidats.MCF = as.numeric_cnu(V14),
      Qualification.Candidats.MCF.femmes = as.numeric_cnu(V15),
      Qualification.Qualifiés.MCF = as.numeric_cnu(V17),
      Qualification.Qualifiés.MCF.femmes = as.numeric_cnu(V18) /100,
      #Qualification.Ratio.MCF = as.numeric_cnu(V19) /100,
      ) %>%
    filter(!is.na(Année)) %>%
    mutate(Périmètre = factor(row_number(), 
                              levels=c(1,2,3,4), 
                              labels = c("Ensemble","Grande discipline","Groupe","Section")),
           .by = c(SectionCNU.ID,Année)) %>%
    left_join(cnu.sections) 
  
  bind_rows(  
    clean_perimetre(qualif %>% mutate(Ensemble = "Ensemble"),"Ensemble","Ensemble","Qualification.Candidats.PR","Qualification.Qualifiés.MCF.femmes"),
    clean_perimetre(qualif,"Grande discipline","GrandeDisciplineCNU.ID","Qualification.Candidats.PR","Qualification.Qualifiés.MCF.femmes"),
    clean_perimetre(qualif,"Groupe","GroupeCNU.ID","Qualification.Candidats.PR","Qualification.Qualifiés.MCF.femmes"),
    clean_perimetre(qualif,"Section","SectionCNU.ID","Qualification.Candidats.PR","Qualification.Qualifiés.MCF.femmes")
  )

}
```

### Recevabilité

```{r qualif.recev, results='asis'}
qualif.ratio.recevabilité <- full_join(
  clean_qualif("cnu-excavation-qualification-2013.csv") %>%
    transmute(Périmètre, Périmètre.ID, Année,
              QC.MCF.13=Qualification.Candidats.MCF, QC.PR.13=Qualification.Candidats.PR),
  clean_qualif("cnu-excavation-qualification-2015.csv") %>%
    transmute(Périmètre, Périmètre.ID, Année,
              QC.MCF.15=Qualification.Candidats.MCF, QC.PR.15=Qualification.Candidats.PR) 
  ) %>%
  mutate(
    ratio.MCF = QC.MCF.15/QC.MCF.13,
    ratio.PR = QC.PR.15/QC.PR.13) %>%
  na.omit() %>%
  summarise(
    ratio.MCF = mean(ratio.MCF),
    ratio.PR = mean(ratio.PR),
    .by = c(Périmètre,Périmètre.ID)
    )

spoiler_table(qualif.ratio.recevabilité)
```

### Bind

```{r qualif.bind, results='asis'}
qualif <- bind_rows(
  clean_qualif("cnu-excavation-qualification-2023.csv"),
  #clean_qualif("cnu-excavation-qualification-2022.csv"),
  #clean_qualif("cnu-excavation-qualification-2021.csv"),
  clean_qualif("cnu-excavation-qualification-2020.csv"),
  #clean_qualif("cnu-excavation-qualification-2019.csv"),
  clean_qualif("cnu-excavation-qualification-2015.csv"),
  clean_qualif("cnu-excavation-qualification-2013.csv") %>%
    left_join(qualif.ratio.recevabilité) %>%
    mutate(
      Qualification.Candidats.MCF = Qualification.Candidats.MCF * ratio.MCF,
      Qualification.Candidats.PR = Qualification.Candidats.PR * ratio.PR) %>%
    select(-c(ratio.MCF,ratio.PR))
) %>% 
  slice_head(n=1, by=c(Périmètre, Périmètre.ID, Année)) %>%
  arrange(Périmètre, Périmètre.ID, Année)

spoiler_table(qualif)
```


## Recrutements

```{r rec.funs}
clean_recrut <- function(csvfile) {
  
  recrut <<- read.csv(csvfile, header = FALSE) %>%
    transmute(
      SectionCNU.ID = as.numeric(V1),
      Année = as.numeric(V3),
      Concours.Postes.PR = as.numeric_cnu(V4),
      Concours.Candidats.PR = as.numeric_cnu(V5),
      Concours.Candidats.PR.femmes = as.numeric_cnu(V6) /100,
      Concours.Recrutés.PR = as.numeric_cnu(V8),
      Concours.Recrutés.PR.femmes = as.numeric_cnu(V9) /100,
      Concours.Postes.MCF = as.numeric_cnu(V13),
      Concours.Candidats.MCF = as.numeric_cnu(V14),
      Concours.Candidats.MCF.femmes = as.numeric_cnu(V15) /100,
      Concours.Recrutés.MCF = as.numeric_cnu(V17),
      Concours.Recrutés.MCF.femmes = as.numeric_cnu(V18) /100,
    ) %>%
    filter(!is.na(Année)) %>%
    mutate(Périmètre = factor(row_number(), 
                              levels=c(1,2,3,4), 
                              labels = c("Ensemble","Grande discipline","Groupe","Section")),
           .by = c(SectionCNU.ID,Année)
           ) %>%
    left_join(cnu.sections)
  
  bind_rows(  
    clean_perimetre(recrut %>% mutate(Ensemble = "Ensemble"),"Ensemble","Ensemble","Concours.Postes.PR","Concours.Recrutés.MCF.femmes"),
    clean_perimetre(recrut,"Grande discipline","GrandeDisciplineCNU.ID","Concours.Postes.PR","Concours.Recrutés.MCF.femmes"),
    clean_perimetre(recrut,"Groupe","GroupeCNU.ID","Concours.Postes.PR","Concours.Recrutés.MCF.femmes"),
    clean_perimetre(recrut,"Section","SectionCNU.ID","Concours.Postes.PR","Concours.Recrutés.MCF.femmes")
  )
  
}
```

```{r rec.bind, results='asis'}
recrut <- bind_rows(
  clean_recrut("cnu-excavation-recrutement-2023.csv"),
  #clean_recrut("cnu-excavation-recrutement-2021.csv"),
  clean_recrut("cnu-excavation-recrutement-2020.csv"),
  #clean_recrut("cnu-excavation-recrutement-2019.csv"),
  clean_recrut("cnu-excavation-recrutement-2015.csv"),
  clean_recrut("cnu-excavation-recrutement-2013.csv")
) %>% 
  slice_head(n=1, by=c(Périmètre, Périmètre.ID, Année)) %>%
  arrange(Périmètre, Périmètre.ID, Année) 

spoiler_table(recrut, trim = Inf)
```


## CNU

```{r cnu, results='asis'}
cnu <- full_join(qualif,recrut) %>%
  # Suppression des sans groupe
  filter(!is.na(Périmètre.ID)) %>% 
  # Fix Erreurs : 
  #  - inversion du nombre de candidats Pharma/ST en 2019 et 2022
  #  - inversion des nombres de candidats et qualifiés Pharma/ST en 2022 
  #  - erreur nombre de candidats groupe 10 pour 2018
  mutate(
    Concours.Candidats.PR = case_when(
      Année == 2019 & Périmètre == "Grande discipline" & Périmètre.ID == "ST" ~ 942,
      Année == 2019 & Périmètre == "Grande discipline" & Périmètre.ID == "Pharma" ~ 29,
      Année == 2022 & Périmètre == "Grande discipline" & Périmètre.ID == "ST" ~ 937,
      Année == 2022 & Périmètre == "Grande discipline" & Périmètre.ID == "Pharma" ~ 29,
      TRUE ~ Concours.Candidats.PR),
    Concours.Candidats.MCF = case_when(
      Année == 2019 & Périmètre == "Grande discipline" & Périmètre.ID == "ST" ~ 2719,
      Année == 2019 & Périmètre == "Grande discipline" & Périmètre.ID == "Pharma" ~ 209,
      Année == 2022 & Périmètre == "Grande discipline" & Périmètre.ID == "ST" ~ 2905,
      Année == 2022 & Périmètre == "Grande discipline" & Périmètre.ID == "Pharma" ~ 224,
      Année == 2018 & Périmètre == "Groupe" & Périmètre.ID == "10" ~ 645,
      TRUE ~ Concours.Candidats.MCF),
    Qualification.Candidats.PR = case_when(
      Année == 2022 & Périmètre == "Grande discipline" & Périmètre.ID == "ST" ~ 231,
      Année == 2022 & Périmètre == "Grande discipline" & Périmètre.ID == "Pharma" ~ 15,
      TRUE ~ Qualification.Candidats.PR),
    Qualification.Candidats.MCF = case_when(
      Année == 2022 & Périmètre == "Grande discipline" & Périmètre.ID == "ST" ~ 3374,
      Année == 2022 & Périmètre == "Grande discipline" & Périmètre.ID == "Pharma" ~ 231,
      TRUE ~ Qualification.Candidats.MCF),
    Qualification.Qualifiés.PR = case_when(
      Année == 2022 & Périmètre == "Grande discipline" & Périmètre.ID == "ST" ~ 180,
      Année == 2022 & Périmètre == "Grande discipline" & Périmètre.ID == "Pharma" ~ 4,
      TRUE ~ Qualification.Qualifiés.PR),
    Qualification.Qualifiés.MCF = case_when(
      Année == 2022 & Périmètre == "Grande discipline" & Périmètre.ID == "ST" ~ 2655,
      Année == 2022 & Périmètre == "Grande discipline" & Périmètre.ID == "Pharma" ~ 167,
      TRUE ~ Qualification.Qualifiés.MCF)
  )

#cnu[!complete.cases(cnu),]

cnu %>% ungroup() %>% 
  pivot_longer(
    -c(Périmètre, Périmètre.ID, Année), 
    names_to = "métrique",
    values_to = "val") %>%
  filter(is.na(val)) %>%
  select(-val) %>%
  write.csv2("valeurs-manquantes.csv", row.names = F)

write.csv2(cnu,"../../data/cpesr-emplois-ec-cnu.csv", row.names = F)

spoiler_table(cnu, trim = Inf)
```


