---
title: "Nombre de postes depuis 2002 pour les sections CNU"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(cowplot)
library(ggcpesrthemes)

knitr::opts_chunk$set(fig.asp=1/1, fig.retina = 2)

theme_cpesr_setup(authors=c("Florent Figon, Julien Gossa"), licence="LO 2.0", source = "DGRH A1-1 — https://github.com/cpesr/emploiESR/")

cnu.sections <- read.csv2("../data/cpesr-cnu-sections.csv")
emploisEC <- read.csv2("../data/cpesr-emplois-ec.csv", stringsAsFactors = TRUE) 

theme_set(theme_cpesr())

source("../R/emploiEC-metriques.R")
# source("../R/emploiEC-plot-series.R")
# source("../R/emploiEC-plot-metrique.R")
source("../R/emploiEC-plot-flux.R")
# source("../R/emploiEC-plot-sections.R")
# source("../R/emploiEC-plot-groupes.R")
# source("../R/emploiEC-plot-contexte.R")

année.ref <- emploisEC %>% filter(Données == "Consolidées") %>% tail(n = 1) %>% pull(Année)

```

```
- twtexte:[#DataESR] Visualisation des concours d'enseignant-chercheur
- twalt:@ffigon @juliengossa.cpesr.fr LO 2.0 www.cpesr.fr
- twurl:https://cpesr.fr/lentree-dans-la-carriere-des-enseignants-chercheurs/
- url:https://cpesr.fr/lentree-dans-la-carriere-des-enseignants-chercheurs/
```


```{r pnp, eval=FALSE}
emploisEC %>% 
  filter(Périmètre == "Grande discipline") %>% 
  mutate(
    `Postes MCF` = Concours.Postes.MCF,
    `Postes non pourvus` = Concours.Postes.MCF - Concours.Recrutés.MCF,
    `Part des postes non pourvus` = 1-(Concours.Recrutés.MCF/Concours.Postes.MCF)) %>% 
  arrange(Année) %>%
  #select(Périmètre.ID,Année,Concours.Postes.MCF, Concours.Recrutés.MCF, pnp, tpnp) %>% 
  filter(!is.na(Périmètre.ID), Périmètre.ID != "Pharma", Périmètre.ID != "Santé") %>%
  pivot_longer(c(`Postes MCF`,`Postes non pourvus`,`Part des postes non pourvus`)) %>%
  mutate(name = factor(name, levels=c("Postes MCF","Postes non pourvus","Part des postes non pourvus"))) %>%
  ggplot(aes(x=Année,y=value,color=Périmètre.ID)) + 
  geom_line() + geom_point() + 
  ylab("") + 
  facet_wrap(name~Périmètre.ID, scales="free_y") +
  ggtitle("Postes MCF : total, non pourvus, et part des non pourvus")
```


```{r funs}

plot_postes <- function(corps, périm="Ensemble", périm.id="Ensemble") {
  df <- emploisEC %>%
    filter(Périmètre == périm, Périmètre.ID == périm.id) %>%
    mutate(Données = case_match(Source,
                                "Galaxie" ~ "Temporaires\n(Galaxie/Odyssée)",
                                "Odyssée" ~ "Temporaires\n(Galaxie/Odyssée)",
                                "CNU" ~ "Définitives (CNU)")) %>% 
    select(Année, Données, 
           !!as.symbol(paste0("Concours.Postes.",corps)),
           !!as.symbol(paste0("Concours.Recrutés.",corps))) %>%
    pivot_longer(-c(Année,Données), names_to = "Postes", values_to = "valeur") %>%
    mutate(Postes = case_match(Postes,
             paste0("Concours.Postes.",corps) ~ "Publiés",
             paste0("Concours.Recrutés.",corps) ~ "Pourvus")) %>%
    filter(!is.na(valeur)) 
  
  df %>%
    ggplot(aes(x=Année, y=valeur,color=Postes)) + 
      geom_smooth(se=F,size=0.5) + 
      geom_point(aes(shape=Données),size=2) + 
      expand_limits(y=0) +
      scale_x_continuous(breaks = c(seq(min(df$Année),2025,5)), minor_breaks = seq(min(df$Année),2025,1)) +
      scale_color_manual(values=c("blue","orange"), breaks=c("Publiés","Pourvus")) +
      #theme_cpesr_cap() + 
      theme(plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm")) +
      labs(y = "Postes", x = "Année") 
}

#plot_postes("MCF", périm="Section", périm.id="27")
#plot_postes("PR", périm="Ensemble", périm.id="Ensemble")
```

```{r batch, results='asis'}

cnus <- cnu.sections %>% filter(GrandeDisciplineCNU != "Santé", GroupeCNU.ID !="11s")
périmètres <- bind_rows(
  cnus %>% transmute(Périmètre = "Grande discipline", Périmètre.ID = GrandeDisciplineCNU.ID, Périmètre.label = GrandeDisciplineCNU),
  cnus %>% transmute(Périmètre = "Groupe", Périmètre.ID = as.character(GroupeCNU.ID), Périmètre.label = GroupeCNU),
  cnus %>% transmute(Périmètre = "Section", Périmètre.ID = as.character(SectionCNU.ID), Périmètre.label = SectionCNU)
) %>%
  unique() %>%
  mutate(
    lab = paste(Périmètre,"CNU",Périmètre.ID,"-",Périmètre.label),
    tit = paste(Périmètre,"CNU",Périmètre.ID),
    subtit = str_wrap(Périmètre.label,80)
  ) %>%
  na.omit() %>%
  add_row(Périmètre = "Ensemble", Périmètre.ID = "Ensemble", Périmètre.label = "Ensemble",
          lab = "Ensemble des sections CNU", tit = "Ensemble des sections CNU", subtit = "",
          .before = 1)

for (ip in 1:nrow(périmètres)) {
  p <- périmètres[ip,"Périmètre"]
  pid <- périmètres[ip,"Périmètre.ID"]
  plab <- périmètres[ip,"Périmètre.label"]
  lab <- périmètres[ip,"lab"]
  tit <- périmètres[ip,"tit"]
  subtit <- périmètres[ip,"subtit"]

  message(tit)

  
  try(cat("\n\n## Evolution du nombre de postes Enseignants-Chercheurs —",lab,"\n\n"))
  
  try(print(
    plot_grid(ncol = 1, rel_widths = c(3,4), align = "hv", axis = "tb", 
      plot_postes("MCF", périm = p, périm.id = pid) +
        ggtitle(paste("Nombre de postes au concours MCF — ",tit), subtitle = subtit) +
        theme(legend.position = "None"),
      plot_postes("PR", périm = p, périm.id = pid) +
        ggtitle(paste("Nombre de postes au concours PR — ",tit), subtitle = subtit)
    )
  ))

  try(print(
    plot_grid(ncol = 1, rel_widths = c(3,2),
      plot_postes("MCF", périm = p, périm.id = pid) +
        ggtitle(paste("Nombre de postes au concours MCF — ",tit), subtitle = subtit) +
        theme_cpesr() +
        theme(legend.position = "right"),     
      plot_grid(nrow = 1, rel_widths = c(10,7), align = "hv", axis = "tb", 
        plot_flux_col(périm = p, périmid = pid, facetting = FALSE) +
          ggtitle(paste("Détails Concours MCF",année.ref)) +
          theme_cpesr() +
          theme(plot.margin = unit(c(0,0,0,0),"cm"),),
        plot_flux_alluvial(périm = p, périmid = pid, facetting = FALSE) +
          #ggtitle(paste("Concours MCF ",année.ref," — ",tit), subtitle = subtit) +
          theme_cpesr_cap() +
          theme(legend.position = "None", 
                axis.title.x = element_blank(), 
                #plot.margin = unit(c(0,0,0,0),"cm"),
                plot.caption = element_text(margin = unit(c(0.5,0,0,0),"cm"))
          )
      )
    )
  ))

    
}
```
